spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:seu-negocio-db} 
    username: ${DATABASE_USERNAME:postgres} 
    password: ${DATABASE_PASSWORD:123456}

logging:
  level:
    br.com.api: DEBUG